project:
  type: book
  preview:
    port: 4200
    browser: true
  # render:
  #   - solution_*.qmd

book:
  title: "Control Challenges: Solutions"
  author: "Iacopo Moles"
  date: "07/07/2025"
  repo-url: https://github.com/icpmoles/controlchallengessolutions
  repo-subdir: docs
  favicon: static/favicon.ico
  site-url: "https://pages.icpmol.es/ControlChallengesSolutions/"
  downloads: [pdf, docx]
  sharing: [facebook, linkedin, twitter]
  open-graph: 
    image: static/header.png
  page-footer: 
    center: "Powered by [Quarto {{version}}](https://quarto.org/) & [Julia Programming Language](https://julialang.org/)" 
   
  chapters:
    - index.qmd
    - solution_01_01.qmd

format:
  html:
    respect-user-color-scheme: true
    toc: true
    theme: 
      light: zephyr
      dark: superhero
    code-fold: true
    code-tools: 
      source: repo
    comments:
      hypothesis: true
    include-in-header:
      - text: |
            <!-- Cloudflare Web Analytics --><script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "8c623441dc9e4fdba21d557cafe1138a"}'></script><!-- End Cloudflare Web Analytics -->
  docx: default
  pdf: default
  ipynb: default



execute:
  freeze: auto  
  cache: true
  daemon: true


engines: ['julia']

authors:
  - name: Iacopo Moles
    affiliation:
    - name: Polytechnic University of Milan
      url: http://www.polimi.it/en
      country: Italy
    url: https://icpmol.es
    email: iacopo@icpmol.es
    degrees: BSc