project:
  type: book
  preview:
    port: 8200
    browser: true
    
book:
  title: "Control Theory: Tutorial with Julia"
  description: "Control Theory with just the right amount of academic rigor"
  open-graph: 
    image: /static/header.png
  output-file: "Control_Tutorial"
  author: "Iacopo Moles"
  repo-url: https://github.com/icpmoles/controltutorial
  repo-subdir: docs
  favicon: /static/favicon.ico
  site-url: "https://pages.icpmol.es/ControlTutorial/"
  downloads: [pdf, docx]
  language: en
  license: CC BY-SA
  reader-mode: true
  sharing: [facebook, linkedin, twitter]
  image: /static/header.png
  page-footer: 
    center: "Powered by [Quarto {{< version >}}](https://quarto.org/) & the [Julia Programming Language](https://julialang.org/)" 
  chapters:
    - index.qmd
    - part: Block on a Slope
      chapters: 
      - block_on_slope/model.qmd
      - block_on_slope/without_friction.qmd
      - block_on_slope/with_friction.qmd
      - block_on_slope/slope.qmd
  appendices:
    - appendix/performance.qmd

format:
  html:
    reference-location: margin
    citation-location: margin
    canonical-url: true
    respect-user-color-scheme: true
    toc: true
    theme: 
      light: flatly
      dark: slate
    code-fold: true
    code-tools: 
      source: repo
    comments:
      hypothesis: true
    include-in-header:
      - text: |
            <!-- Cloudflare Web Analytics --><script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "8c623441dc9e4fdba21d557cafe1138a"}'></script><!-- End Cloudflare Web Analytics -->
    grid:
      sidebar-width: 250px
      body-width: 1420px
      margin-width: 250px
      gutter-width: 1.5rem
  docx: default
  pdf:
    reference-location: margin
    citation-location: margin
    papersize: a4
    fontsize: 8pt
    keep-tex: true
    pdf-engine: lualatex 
    code-overflow: wrap
    sansfont: Inter
    monofont: JuliaMono
    mathfont: Stix Two Math
    mainfont: Tex-Gyre Pagella
    geometry:
      - top=25mm
      - left=15mm
      - right=15mm
      - heightrounded
    links-as-notes: true
    pdfa: true
    includesource: true
    pagestyle: fancy
    metadata:
      subject: "Control Theory with just the right amount of academic rigor"
      keywords: 
      - control theory
      - linear control
      - non-linear control
      - modeling
      - simulation
      - tutorial
      - FMU
      - openmodelica
      - julia
      - ControlSystems.jl
    include-in-header: 
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
          commandchars=\\\{\},
          breaklines, breaknonspaceingroup, breakanywhere
        }
    include-before-body:
      text: |
        \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
          showspaces = false,
          showtabs = false,
          breaksymbolleft={},
          breaklines
          % Note: setting commandchars=\\\{\} here will cause an error 
        }



execute:
  freeze: auto  
  cache: true
  daemon: true


engines: ['julia']

authors:
  - name: Iacopo Moles
    affiliation:
    - name: Polytechnic University of Milan
      url: http://www.polimi.it/en
      country: Italy
      ror: 01nffqt88
    url: https://icpmol.es
    email: iacopo@icpmol.es
