project:
  type: book
  preview:
    port: 8200
    browser: true

book:
  title: "Control Challenges: Solutions"
  description: "Control Theory with just the right amount of academic rigor"
  open-graph: 
    image: _static/header.png
  output-file: "Control_Challenges-solutions"
  author: "Iacopo Moles"
  repo-url: https://github.com/icpmoles/controlchallengessolutions
  repo-subdir: docs
  favicon: _static/favicon.ico
  site-url: "https://pages.icpmol.es/ControlChallengesSolutions/"
  downloads: [pdf, docx]
  language: en
  license: CC BY-SA
  reader-mode: true
  sharing: [facebook, linkedin, twitter]
  image: _static/header.png
  page-footer: 
    center: "Powered by [Quarto {{< version >}}](https://quarto.org/) & the [Julia Programming Language](https://julialang.org/)" 
  chapters:
    - index.qmd
    - part: block_on_slope/model.qmd
      chapters: 
      - block_on_slope/without_friction.qmd
      - block_on_slope/with_friction.qmd
      - block_on_slope/slope.qmd
  appendices:
    - appendix/performance.qmd

format:
  html:
    reference-location: margin
    citation-location: margin
    canonical-url: true
    respect-user-color-scheme: true
    toc: true
    theme: 
      light: zephyr
      dark: superhero
    code-fold: true
    code-tools: 
      source: repo
    comments:
      hypothesis: true
    include-in-header:
      - text: |
            <!-- Cloudflare Web Analytics --><script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "8c623441dc9e4fdba21d557cafe1138a"}'></script><!-- End Cloudflare Web Analytics -->
  docx: default
  pdf:
    papersize: a4
    keep-tex: true
    pdf-engine: lualatex 
    code-overflow: wrap
    sansfont: Berkeley Mono
    monofont: JuliaMono
    mathfont: Stix Two Math
    mainfont: Inter
    metadata:
      subject: "Control Theory with just the right amount of academic rigor"
      keywords: 
      - control theory
      - linear control
      - non-linear control
      - modeling
      - simulation
      - tutorial
      - FMU
      - openmodelica
      - julia
      - ControlSystems.jl
    include-in-header: 
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
          commandchars=\\\{\},
          breaklines, breaknonspaceingroup, breakanywhere
        }
    include-before-body:
      text: |
        \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
          showspaces = false,
          showtabs = false,
          breaksymbolleft={},
          breaklines
          % Note: setting commandchars=\\\{\} here will cause an error 
        }



execute:
  freeze: auto  
  cache: true
  daemon: true


engines: ['julia']

authors:
  - name: Iacopo Moles
    affiliation:
    - name: Polytechnic University of Milan
      url: http://www.polimi.it/en
      country: Italy
      ror: 01nffqt88
    url: https://icpmol.es
    email: iacopo@icpmol.es
    degrees: BSc