project:
  type: book

book:
  title: "Control Challenges: Solutions"
  author: "Iacopo Moles"
  date: "07/07/2025"
  chapters:
    - index.qmd
    - solution_01_01.qmd

format:
  html:
    theme: 
      light: zephyr
      dark: superhero
    comments:
      hypothesis: true
    include-in-header:
      - text: |
            <!-- Cloudflare Web Analytics --><script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "8c623441dc9e4fdba21d557cafe1138a"}'></script><!-- End Cloudflare Web Analytics -->
  docx: default
  pdf: default

execute:
  freeze: true
  cache: true

engines: ['julia']

