on:
  push:
    branches:
      - main

name: Render and Publish

# you need these permissions to publish to GitHub pages
permissions: 
    contents: write
    pages: write
    id-token: write

env:
  QUARTO_VERSION: '1.7.32'
  JULIA_VERSION: '1.11.10'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Fonts from TTF
        run: |
          cp -r  docs/_3rdparty/fonts /usr/share/fonts/
          fc-cache -f -v
      
      - name: Install Software Dependencies
        run: sudo apt-get install --no-install-recommends librsvg2-bin fontconfig qpdf
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@9e48da27e184aa238fcb49f5db75469626d43adb
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true 
          version: ${{ env.QUARTO_VERSION }}

      - name: Load Julia packages from cache
        id: julia-cache
        uses: julia-actions/cache@d10a6fd8f31b12404a54613ebad242900567f2b9     

      - name: Setup Julia
        if: steps.julia-cache.outputs.cache-hit != 'true'
        uses: julia-actions/setup-julia@5c9647d97b78a5debe5164e9eec09d653d29bd71
        with:
          version: ${{ env.JULIA_VERSION }}

      - run: julia --project -e 'using Pkg; Pkg.instantiate()'
      # See more at https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-03-dependencies.md

      - name: Render with Quarto
        uses: quarto-dev/quarto-actions/render@9e48da27e184aa238fcb49f5db75469626d43adb
        with:
          path: docs
      
      - name: Linearize PDF
        run: qpdf docs/_book/Control_Tutorial.pdf --linearize --replace-input

      - name: Upload GHPages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
        with:
          path: ./docs/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e


        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

      - name: Save Julia depot cache on cancel or failure
        id: julia-cache-save
        if: cancelled() || failure()
        uses: actions/cache/save@v4
        with: 
          path: |
            ${{ steps.julia-cache.outputs.cache-paths }}
          key: ${{ steps.julia-cache.outputs.cache-key }}


