on:
  push:
    branches:
      - main

name: Render and Publish

# you need these permissions to publish to GitHub pages
permissions: 
    contents: write
    pages: write

env:
  QUARTO_VERSION: '1.7.29'
  JULIA_VERSION: '1.11.5'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@9e48da27e184aa238fcb49f5db75469626d43adb
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          version: ${{ env.QUARTO_VERSION }}

      - run: sudo apt-get install librsvg2-bin

      - name: Load Julia packages from cache
        id: julia-cache
        uses: julia-actions/cache@d10a6fd8f31b12404a54613ebad242900567f2b9     

      # From https://github.com/julia-actions/setup-julia
      - name: Setup Julia
        if: steps.julia-cache.outputs.cache-hit != 'true'
        uses: julia-actions/setup-julia@5c9647d97b78a5debe5164e9eec09d653d29bd71
        with:
          version: ${{ env.JULIA_VERSION }}

      - run: julia --project -e 'using Pkg; Pkg.instantiate()'
      # See more at https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-03-dependencies.md

      # NOTE: If Publishing to GitHub Pages, set the permissions correctly (see top of this yaml)
      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/publish@9e48da27e184aa238fcb49f5db75469626d43adb
        with:
          path: docs
          target: gh-pages
          GITHUB_EMAIL: 8940011+icpmoles@users.noreply.github.com
          GITHUB_USERNAME: icpmoles
          render: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

      - name: Save Julia depot cache on cancel or failure
        id: julia-cache-save
        if: cancelled() || failure()
        uses: actions/cache/save@v4
        with: 
          path: |
            ${{ steps.julia-cache.outputs.cache-paths }}
          key: ${{ steps.julia-cache.outputs.cache-key }}
