name: Format suggestions
on:
    - pull_request
    - push
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - run: cd src

      - uses: julia-actions/julia-format@d758beeb6b381459ef1254656f351627155a0f0a
